// Pre-generated research dossiers, committed as app data so every user sees
// them by default in speaker/company profiles (generated by
// scrape/research-gen.mjs). Keyed by speaker/org id.
import researchJson from "@/data/research.json";

export interface StoredResearch {
  summary: string;
  bullets: string[];
  generatedAt?: string;
}

const data = researchJson as Record<string, StoredResearch>;

// Some short/ambiguous names (e.g. "ARD", "EY") yield a "couldn't determine which
// organization" non-answer — show the live Research button for those instead.
const NON_ANSWER =
  /^(i need more information|i couldn'?t|i could not|i was unable|no reliable information|i don'?t have)|(very short name|too (generic|ambiguous)|could refer to (many|several)|is ambiguous)/i;

export function getResearch(id: string): StoredResearch | null {
  const r = data[id];
  if (!r || !r.summary || NON_ANSWER.test(r.summary)) return null;
  return r;
}
